### ISSUE TITLE
Doesn't work on windows.

### ISSUE THREAD

**Issue by esciron** [tdrussell/diffusion-pipe#3] opened 2024-12-12 15:25 UTC
**Deepspeed keeps trying to use linux libraries**:

```
LINK : fatal error LNK1181: cannot open input file 'aio.lib'
test.c
LINK : fatal error LNK1181: cannot open input file 'cufile.lib'
W1212 16:11:31.483000 48056 site-packages\torch\distributed\elastic\multiprocessing\redirects.py:29] NOTE: Redirects are currently not supported in Windows or MacOs.
[2024-12-12 16:11:32,371] [WARNING] [runner.py:212:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
[2024-12-12 16:11:32,381] [INFO] [runner.py:585:main] cmd = my python location\python.exe -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMF19 --master_addr=127.0.0.1 --master_port=29500 --enable_each_rank_log=None train.py --deepspeed --config examples/hunyuan_video.toml
[2024-12-12 16:11:33,726] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
test.c
LINK : fatal error LNK1181: cannot open input file 'aio.lib'
test.c
LINK : fatal error LNK1181: cannot open input file 'cufile.lib'
W1212 16:11:42.089000 46972 site-packages\torch\distributed\elastic\multiprocessing\redirects.py:29] NOTE: Redirects are currently not supported in Windows or MacOs.
[2024-12-12 16:11:44,864] [INFO] [comm.py:652:init_distributed] cdb=None
[2024-12-12 16:11:44,864] [INFO] [comm.py:683:init_distributed] Initializing TorchBackend in DeepSpeed with backend gloo
Traceback (most recent call last):
  File "E:\diffusion-pipe\train.py", line 204, in <module>
    deepspeed.init_distributed()
  File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\site-packages\deepspeed\comm\comm.py", line 685, in init_distributed
    cdb = TorchBackend(dist_backend, timeout, init_method, rank, world_size)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\site-packages\deepspeed\comm\torch.py", line 112, in __init__
    self.init_process_group(backend, timeout, init_method, rank, world_size)
  File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\site-packages\deepspeed\comm\torch.py", line 142, in init_process_group
    torch.distributed.init_process_group(backend,
  File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\distributed\c10d_logger.py", line 81, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\distributed\c10d_logger.py", line 95, in wrapper
    func_return = func(*args, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\distributed\distributed_c10d.py", line 1714, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\distributed\rendezvous.py", line 274, in _env_rendezvous_handler
    store = _create_c10d_store(
            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\distributed\rendezvous.py", line 194, in _create_c10d_store
    return TCPStore(
           ^^^^^^^^^
RuntimeError: use_libuv was requested but PyTorch was build without libuv support
[2024-12-12 16:11:45,677] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 46972
[2024-12-12 16:11:45,681] [ERROR] [launch.py:325:sigkill_handler] ['C:\\Users\\username\\AppData\\Local\\Programs\\Python\\Python311\\python.exe', '-u', 'train.py', '--local_rank=0', '--deepspeed', '--config', 'examples/hunyuan_video.toml'] exits with return code = 1
```

Tried with my local install and with conda env, same problem across the board.
Tested Python 3.11 and 3.12.
Tested cuda 12.4 and 12.6
Made sure always that cuda was true etc.

Edit: If you are on windows don't waste your time, deepspeed is not going to work.

**Comment by tdrussell** [comment] 2024-12-12 16:23
Ok, thanks for reporting this. I'll update the README. There are reports that the training script does work if you use WSL 2. You might give that a try.

**Comment by NeilsMabet** [comment] 2024-12-12 23:41
I can confirm it works on WSL Ubuntu under Windows. Overall it's actually is rather hard to train on videos, I succeded only on 1 short video at a time, but i have a blast with training on pictures.

**Comment by tdrussell** [comment] 2024-12-14 04:50
Going to close this. The README is now updated to mention the lack of windows support and recommend WSL.

**Closed by tdrussell** 2024-12-14 04:50 UTC

**Comment by zeldapkmn** [comment] 2024-12-16 21:27
> I can confirm it works on WSL Ubuntu under Windows. Overall it's actually is rather hard to train on videos, I succeded only on 1 short video at a time, but i have a blast with training on pictures.

What do your parameters/dataset look like for images?

**Comment by NeilsMabet** [comment] 2024-12-16 23:43
> What do your parameters/dataset look like for images?

For example: i made five different 512*512 images of my acquaintance, with .txt files with the same name as image-files. Used simple blip captions like "there is a woman with red hair and earrings posing for a picture". And then trained for like 20 epochs with 10 repeats with checkpoint save every 5 epochs.

**Comment by zeldapkmn** [comment] 2024-12-17 00:42
> > What do your parameters/dataset look like for images?
> 
> For example: i made five different 512*512 images of my acquaintance, with .txt files with the same name as image-files. Used simple blip captions like "there is a woman with red hair and earrings posing for a picture". And then trained for like 20 epochs with 10 repeats with checkpoint save every 5 epochs.

1. Could 10 repeats cause overfitting with a dataset that small?
2. How long did it take overall?
3. Does the input image size have to be 1:1? I assumed not, since padding and aspect ratio bucketing were present. I didn't want to lose vertical data
4. Would setting resolution to 2048 x 2048 be too much for a 4090 32GB RAM?

Mine trains at a crawl, and I haven't gotten it to succeed yet (dies within 5-10 steps)

**Comment by NeilsMabet** [comment] 2024-12-17 05:12
> > > What do your parameters/dataset look like for images?
> > 
> > 
> > For example: i made five different 512*512 images of my acquaintance, with .txt files with the same name as image-files. Used simple blip captions like "there is a woman with red hair and earrings posing for a picture". And then trained for like 20 epochs with 10 repeats with checkpoint save every 5 epochs.
> 
>     1. Could 10 repeats cause overfitting with a dataset that small?
> 
>     2. How long did it take overall?
> 
>     3. Does the input image size have to be 1:1? I assumed not, since padding and aspect ratio bucketing were present. I didn't want to lose vertical data
> 
>     4. Would setting resolution to 2048 x 2048 be too much for a 4090 32GB RAM?
> 
> 
> Mine trains at a crawl, and I haven't gotten it to succeed yet (dies within 5-10 steps)

1. Well, yeah, but i wanted a fast result with a high level of likeness to test output fast. The results were not always coherent, but good enough on 10-15 epochs. Also, lr = 5e-4
2. Half an hour maybe. 
3. No, i guess not, my other tests show that other non square resolutions are fine.
4. I don't know, really, no expert, just a user.
